//! Zero-copy word vector storage and operations
//!
//! Copyright 2026 COOLJAPAN OU (Team KitaSan)
//!
//! Implements memory-mapped word embeddings with zero-copy access.
//! Based on architecture design in docs/007.md.
//!
//! # Binary Format
//!
//! ```text
//! [ Header (32 bytes) ]
//! [ Vector 0 (dim * 4 bytes) ]
//! [ Vector 1 (dim * 4 bytes) ]
//! ...
//! [ Vector N ]
//! ```

use crate::{Error, Result};
use bytemuck::{Pod, Zeroable};
use memmap2::Mmap;
use std::fs::File;
use std::sync::Arc;

/// Magic number "MCV1" for vectors.bin format
const MAGIC: u32 = 0x3143_564D; // "MCV1" in little-endian

/// Data type identifier for vector elements
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum VectorDataType {
    /// 32-bit floating point (4 bytes per element)
    F32 = 0,
    /// 16-bit floating point (2 bytes per element)
    F16 = 1,
    /// 8-bit integer (1 byte per element, quantized)
    I8 = 2,
}

impl VectorDataType {
    /// Size in bytes per vector element
    pub const fn element_size(&self) -> usize {
        match self {
            Self::F32 => 4,
            Self::F16 => 2,
            Self::I8 => 1,
        }
    }

    /// Convert from u32
    fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::F32),
            1 => Some(Self::F16),
            2 => Some(Self::I8),
            _ => None,
        }
    }
}

/// Vector store header (32 bytes, C-compatible layout)
#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct VectorHeader {
    /// Magic number "MCV1"
    magic: u32,
    /// Number of words in vocabulary
    vocab_size: u32,
    /// Vector dimensionality (e.g., 300)
    dim: u32,
    /// Data type (0=f32, 1=f16, 2=i8)
    data_type: u32,
    /// Reserved for future use
    reserved: [u32; 4],
}

// Safety: VectorHeader is repr(C) with only u32 fields
unsafe impl Pod for VectorHeader {}
unsafe impl Zeroable for VectorHeader {}

/// Vocabulary index mapping word_id → surface form.
///
/// Loaded from a companion TSV file: `<word_id>\t<surface>\n`
/// Generated by `kizame dict dump --vocab-surface` or by the tokenizer.
#[derive(Debug, Default, Clone)]
pub struct VocabIndex {
    /// Maps word_id → surface string
    id_to_surface: std::collections::HashMap<u32, String>,
}

impl VocabIndex {
    /// Load from a tab-separated file: `word_id\tsurface\n`
    pub fn from_tsv(path: impl AsRef<std::path::Path>) -> Result<Self> {
        use std::io::{BufRead, BufReader};
        let file = std::fs::File::open(path.as_ref())
            .map_err(|e| Error::VectorError(format!("Failed to open vocab TSV: {e}")))?;
        let reader = BufReader::new(file);
        let mut id_to_surface = std::collections::HashMap::new();
        for line_result in reader.lines() {
            let line = line_result
                .map_err(|e| Error::VectorError(format!("IO error reading TSV: {e}")))?;
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut parts = line.splitn(2, '\t');
            let id_str = parts.next().unwrap_or("");
            let surface = parts.next().unwrap_or("").to_string();
            if let Ok(id) = id_str.parse::<u32>() {
                id_to_surface.insert(id, surface);
            }
        }
        Ok(Self { id_to_surface })
    }

    /// Look up surface form for a word_id
    pub fn surface_of(&self, word_id: u32) -> Option<&str> {
        self.id_to_surface.get(&word_id).map(|s| s.as_str())
    }

    /// Number of entries in the index
    pub fn len(&self) -> usize {
        self.id_to_surface.len()
    }

    /// True if the index is empty
    pub fn is_empty(&self) -> bool {
        self.id_to_surface.is_empty()
    }
}

/// Zero-copy word vector store
///
/// Provides fast access to pre-trained word embeddings without parsing or copying.
/// Vectors are accessed directly from memory-mapped file.
pub struct VectorStore {
    /// Memory-mapped file
    _mmap: Arc<Mmap>,
    /// Pointer to vector data (after header)
    data_ptr: *const u8,
    /// Vector dimensionality
    dim: usize,
    /// Vocabulary size
    vocab_size: usize,
    /// Data type of vectors
    data_type: VectorDataType,
    /// Quantization scale (for I8 dtype; `reserved[0]` bits in header)
    quant_scale: Option<f32>,
    /// Optional vocabulary index mapping word_id → surface form
    vocab: Option<VocabIndex>,
}

// Safety: The data_ptr points to immutable memory-mapped data
unsafe impl Send for VectorStore {}
unsafe impl Sync for VectorStore {}

impl std::fmt::Debug for VectorStore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VectorStore")
            .field("vocab_size", &self.vocab_size)
            .field("dim", &self.dim)
            .field("data_type", &self.data_type)
            .finish()
    }
}

impl VectorStore {
    /// Header size in bytes
    const HEADER_SIZE: usize = 32;

    /// Load vector store from memory-mapped file
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - File cannot be opened or mapped
    /// - File is too small for header
    /// - Header magic number is invalid
    /// - Data type is unsupported
    /// - File size doesn't match expected size
    pub fn from_mmap(mmap: Arc<Mmap>) -> Result<Self> {
        let data = &mmap[..];

        // Validate minimum size
        if data.len() < Self::HEADER_SIZE {
            return Err(Error::VectorError(
                "Vector file too small for header".to_string(),
            ));
        }

        // Read and validate header
        let header: VectorHeader = bytemuck::pod_read_unaligned(&data[0..Self::HEADER_SIZE]);

        if header.magic != MAGIC {
            return Err(Error::VectorError(format!(
                "Invalid magic number: expected 0x{:08X}, got 0x{:08X}",
                MAGIC, header.magic
            )));
        }

        let data_type = VectorDataType::from_u32(header.data_type).ok_or_else(|| {
            Error::VectorError(format!("Invalid data type: {}", header.data_type))
        })?;

        let vocab_size = header.vocab_size as usize;
        let dim = header.dim as usize;

        // Validate file size
        let element_size = data_type.element_size();
        let expected_size = Self::HEADER_SIZE + (vocab_size * dim * element_size);

        if data.len() != expected_size {
            return Err(Error::VectorError(format!(
                "Vector file size mismatch: expected {} bytes, got {}",
                expected_size,
                data.len()
            )));
        }

        // Get pointer to vector data
        let data_ptr = data[Self::HEADER_SIZE..].as_ptr();

        // For I8 quantization, `reserved[0]` stores the scale as an f32 bit pattern.
        let quant_scale = if data_type == VectorDataType::I8 && header.reserved[0] != 0 {
            Some(f32::from_bits(header.reserved[0]))
        } else {
            None
        };

        Ok(Self {
            _mmap: mmap,
            data_ptr,
            dim,
            vocab_size,
            data_type,
            quant_scale,
            vocab: None,
        })
    }

    /// Load vector store from file path
    ///
    /// # Errors
    ///
    /// Returns an error if file cannot be opened or is invalid.
    pub fn from_file(path: impl AsRef<std::path::Path>) -> Result<Self> {
        let file = File::open(path).map_err(|e| Error::VectorError(e.to_string()))?;
        let mmap = unsafe { Mmap::map(&file).map_err(|e| Error::VectorError(e.to_string()))? };
        Self::from_mmap(Arc::new(mmap))
    }

    /// Get vector by word ID (zero-copy)
    ///
    /// Returns a slice directly referencing the memory-mapped data.
    /// No copying occurs.
    ///
    /// # Arguments
    ///
    /// * `word_id` - Index of the word in vocabulary
    ///
    /// # Returns
    ///
    /// `None` if word_id is out of bounds, otherwise a slice of f32 values.
    #[inline]
    pub fn get(&self, word_id: u32) -> Option<&[f32]> {
        if self.data_type != VectorDataType::F32 {
            // For now, only support F32
            return None;
        }

        let word_id = word_id as usize;
        if word_id >= self.vocab_size {
            return None;
        }

        let element_size = self.data_type.element_size();
        let start = word_id * self.dim * element_size;

        // Safety: We validated bounds and data type
        unsafe {
            let slice =
                std::slice::from_raw_parts(self.data_ptr.add(start), self.dim * element_size);
            Some(bytemuck::cast_slice(slice))
        }
    }

    /// Get a dequantized f32 vector for any supported data type.
    ///
    /// - **F32**: Returns a borrowed slice (zero-copy) wrapped in [`std::borrow::Cow::Borrowed`].
    /// - **F16**: Decodes each element from IEEE-754 half-precision to f32 (allocates).
    /// - **I8**: Linearly dequantizes `i8 * scale → f32` using the per-store scale (allocates).
    pub fn get_dequantized(&self, word_id: u32) -> Option<std::borrow::Cow<'_, [f32]>> {
        let idx = word_id as usize;
        if idx >= self.vocab_size {
            return None;
        }
        match self.data_type {
            VectorDataType::F32 => self.get(word_id).map(std::borrow::Cow::Borrowed),
            VectorDataType::F16 => {
                let start = idx * self.dim * 2;
                let bytes =
                    unsafe { std::slice::from_raw_parts(self.data_ptr.add(start), self.dim * 2) };
                let u16s: &[u16] = bytemuck::cast_slice(bytes);
                Some(std::borrow::Cow::Owned(
                    u16s.iter().map(|&b| f16_to_f32(b)).collect(),
                ))
            }
            VectorDataType::I8 => {
                let start = idx * self.dim;
                let bytes =
                    unsafe { std::slice::from_raw_parts(self.data_ptr.add(start), self.dim) };
                let i8s: &[i8] = bytemuck::cast_slice(bytes);
                let scale = self.quant_scale.unwrap_or(1.0_f32);
                Some(std::borrow::Cow::Owned(
                    i8s.iter().map(|&b| b as f32 * scale).collect(),
                ))
            }
        }
    }

    /// Get vector dimensionality
    #[inline]
    pub const fn dim(&self) -> usize {
        self.dim
    }

    /// Get vocabulary size
    #[inline]
    pub const fn vocab_size(&self) -> usize {
        self.vocab_size
    }

    /// Get data type
    #[inline]
    pub const fn data_type(&self) -> VectorDataType {
        self.data_type
    }

    /// Compute mean pooling of multiple vectors (sentence embedding)
    ///
    /// Takes the average of all input vectors to create a single
    /// sentence-level representation.
    ///
    /// # Arguments
    ///
    /// * `word_ids` - IDs of words to average
    ///
    /// # Returns
    ///
    /// Mean-pooled vector, or None if no valid vectors found.
    pub fn mean_pooling(&self, word_ids: &[u32]) -> Option<Vec<f32>> {
        let mut sum = vec![0.0_f32; self.dim];
        let mut count = 0;

        for &word_id in word_ids {
            if let Some(vec) = self.get_dequantized(word_id) {
                for (s, &val) in sum.iter_mut().zip(vec.iter()) {
                    *s += val;
                }
                count += 1;
            }
        }

        if count == 0 {
            return None;
        }

        let count_f32 = count as f32;
        for val in sum.iter_mut() {
            *val /= count_f32;
        }

        Some(sum)
    }

    /// Attach a `VocabIndex` to this store (builder pattern).
    ///
    /// The vocab index maps word_id → surface form, enabling human-readable
    /// results from k-NN queries.
    #[must_use]
    pub fn with_vocab(mut self, vocab: VocabIndex) -> Self {
        self.vocab = Some(vocab);
        self
    }

    /// Load vector store from file path, also loading a companion vocab TSV.
    ///
    /// # Errors
    ///
    /// Returns an error if either file cannot be opened or is invalid.
    pub fn from_file_with_vocab(
        vec_path: impl AsRef<std::path::Path>,
        vocab_path: impl AsRef<std::path::Path>,
    ) -> Result<Self> {
        let store = Self::from_file(vec_path)?;
        let vocab = VocabIndex::from_tsv(vocab_path)?;
        Ok(store.with_vocab(vocab))
    }

    /// Look up surface form for a word_id (requires vocab index to be loaded).
    ///
    /// Returns `None` if no vocab index is attached or the word_id is not found.
    pub fn surface_of(&self, word_id: u32) -> Option<&str> {
        self.vocab.as_ref()?.surface_of(word_id)
    }

    /// Iterate over all `(word_id, vector)` pairs in the store.
    ///
    /// Skips out-of-bounds word IDs and all-zero vectors (untrained/padding
    /// entries). The iterator yields `(word_id, &[f32])` pairs in ascending
    /// word_id order.
    ///
    /// Only F32 vectors are currently supported; non-F32 stores yield nothing.
    pub fn all_vectors(&self) -> impl Iterator<Item = (u32, &[f32])> {
        (0..self.vocab_size as u32).filter_map(move |id| {
            let vec = self.get(id)?;
            // Skip all-zero vectors (untrained words / padding)
            if vec.iter().all(|&x| x == 0.0) {
                return None;
            }
            Some((id, vec))
        })
    }

    /// Find the `n` most similar vectors to `query` by cosine similarity.
    ///
    /// Performs an exhaustive linear scan over all non-zero vectors in the
    /// store.  This is O(V × D) in vocabulary size and vector dimension, which
    /// is acceptable for typical MeCab-scale vocabularies (≤ 400 k entries).
    ///
    /// # Arguments
    ///
    /// * `query`   – Query embedding slice (must have length == `self.dim()`).
    /// * `n`       – Maximum number of results to return.
    /// * `exclude` – Word IDs to omit from results (e.g. the query word itself).
    ///
    /// # Returns
    ///
    /// A `Vec<(word_id, cosine_similarity)>` sorted in descending similarity
    /// order, with at most `n` entries.  Returns an empty vec if `n == 0` or
    /// the query is an all-zero vector.
    pub fn most_similar_by_vec(&self, query: &[f32], n: usize, exclude: &[u32]) -> Vec<(u32, f32)> {
        if n == 0 || query.iter().all(|&x| x == 0.0) {
            return vec![];
        }

        let exclude_set: std::collections::HashSet<u32> = exclude.iter().copied().collect();

        let mut scores: Vec<(u32, f32)> = self
            .all_vectors()
            .filter(|(id, _)| !exclude_set.contains(id))
            .filter_map(|(id, vec)| Self::cosine_similarity(query, vec).map(|s| (id, s)))
            .collect();

        // Partial sort: we only need the top-n entries.
        // `select_nth_unstable_by` puts the n-th largest in position n and
        // guarantees that all elements before it are ≥ it, which lets us
        // truncate cheaply before the final stable sort.
        if scores.len() > n {
            scores.select_nth_unstable_by(n, |a, b| {
                b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal)
            });
            scores.truncate(n);
        }

        scores.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        scores
    }

    /// Compute cosine similarity between two vectors
    ///
    /// # Arguments
    ///
    /// * `a` - First vector
    /// * `b` - Second vector
    ///
    /// # Returns
    ///
    /// Cosine similarity in range [-1.0, 1.0], or None if vectors are zero.
    pub fn cosine_similarity(a: &[f32], b: &[f32]) -> Option<f32> {
        if a.len() != b.len() {
            return None;
        }

        let mut dot = 0.0_f32;
        let mut norm_a = 0.0_f32;
        let mut norm_b = 0.0_f32;

        for i in 0..a.len() {
            dot += a[i] * b[i];
            norm_a += a[i] * a[i];
            norm_b += b[i] * b[i];
        }

        let denom = norm_a.sqrt() * norm_b.sqrt();
        if denom < 1e-10 {
            return None;
        }

        Some(dot / denom)
    }
}

// ── F16 ↔ F32 converters (manual IEEE-754, no extra crate) ───────────────────

/// Decode a 16-bit IEEE-754 half-precision bit pattern to f32.
fn f16_to_f32(bits: u16) -> f32 {
    let sign = (bits >> 15) as u32;
    let exp = ((bits >> 10) & 0x1F) as u32;
    let mant = (bits & 0x3FF) as u32;
    let bits32: u32 = if exp == 0 {
        if mant == 0 {
            sign << 31 // ±zero
        } else {
            // subnormal: normalise
            let e = mant.leading_zeros() - 22;
            (sign << 31) | ((127 - 14 - e) << 23) | ((mant << (e + 1)) & 0x7F_FFFF)
        }
    } else if exp == 31 {
        (sign << 31) | 0x7F80_0000 | (mant << 13) // ±inf / NaN
    } else {
        (sign << 31) | ((exp + 127 - 15) << 23) | (mant << 13)
    };
    f32::from_bits(bits32)
}

/// Encode an f32 to a 16-bit IEEE-754 half-precision bit pattern (with saturation).
fn f32_to_f16(val: f32) -> u16 {
    let bits = val.to_bits();
    let sign = ((bits >> 31) & 1) as u16;
    let exp = ((bits >> 23) & 0xFF) as i32;
    let mant = bits & 0x7F_FFFF;
    if exp == 0xFF {
        return (sign << 15) | 0x7C00 | u16::from(mant != 0); // inf/NaN
    }
    let exp16 = exp - 127 + 15;
    if exp16 >= 31 {
        return (sign << 15) | 0x7C00; // overflow → infinity
    }
    if exp16 <= 0 {
        if exp16 < -10 {
            return sign << 15; // underflow → zero
        }
        let m = (mant | 0x80_0000) >> (1 - exp16);
        return (sign << 15) | (m >> 13) as u16;
    }
    (sign << 15) | ((exp16 as u16) << 10) | (mant >> 13) as u16
}

// ── Quantization writers (emit full MCV1-format byte buffers) ────────────────

/// Build a complete MCV1 binary buffer with F16-quantized vectors.
///
/// Encodes each f32 element to an IEEE-754 half-precision u16.
/// Suitable for passing to [`VectorStore::from_mmap`] after writing to a file.
pub fn quantize_f16(vectors: &[f32], vocab_size: usize, dim: usize) -> Vec<u8> {
    use bytemuck::bytes_of;
    assert_eq!(vectors.len(), vocab_size * dim, "vectors length mismatch");
    let data_bytes = vocab_size * dim * 2; // 2 bytes per f16
    let total = 32 + data_bytes;
    let mut buf = Vec::with_capacity(total);
    let header = VectorHeader {
        magic: MAGIC,
        vocab_size: vocab_size as u32,
        dim: dim as u32,
        data_type: VectorDataType::F16 as u32,
        reserved: [0u32; 4],
    };
    buf.extend_from_slice(bytes_of(&header));
    for &v in vectors {
        let half = f32_to_f16(v);
        buf.extend_from_slice(&half.to_le_bytes());
    }
    buf
}

/// Build a complete MCV1 binary buffer with I8-quantized vectors.
///
/// Uses per-store linear quantization: `scale = max_abs / 127.0`.
/// Returns `(bytes, scale)` — store `scale` or persist it via the header's
/// `reserved[0]` field (already encoded as `f32::to_bits(scale)`).
pub fn quantize_i8(vectors: &[f32], vocab_size: usize, dim: usize) -> (Vec<u8>, f32) {
    use bytemuck::bytes_of;
    assert_eq!(vectors.len(), vocab_size * dim, "vectors length mismatch");
    let max_abs = vectors.iter().copied().fold(0.0_f32, |m, v| m.max(v.abs()));
    let scale = if max_abs > 0.0 {
        max_abs / 127.0
    } else {
        1.0_f32
    };
    let inv = 1.0 / scale;
    let total = 32 + vocab_size * dim;
    let mut buf = Vec::with_capacity(total);
    let mut reserved = [0u32; 4];
    reserved[0] = scale.to_bits(); // persist scale in reserved[0]
    let header = VectorHeader {
        magic: MAGIC,
        vocab_size: vocab_size as u32,
        dim: dim as u32,
        data_type: VectorDataType::I8 as u32,
        reserved,
    };
    buf.extend_from_slice(bytes_of(&header));
    for &v in vectors {
        let q = (v * inv).round().clamp(-128.0, 127.0) as i8;
        buf.push(q as u8);
    }
    (buf, scale)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vector_data_type() {
        assert_eq!(VectorDataType::F32.element_size(), 4);
        assert_eq!(VectorDataType::F16.element_size(), 2);
        assert_eq!(VectorDataType::I8.element_size(), 1);

        assert_eq!(VectorDataType::from_u32(0), Some(VectorDataType::F32));
        assert_eq!(VectorDataType::from_u32(1), Some(VectorDataType::F16));
        assert_eq!(VectorDataType::from_u32(2), Some(VectorDataType::I8));
        assert_eq!(VectorDataType::from_u32(99), None);
    }

    #[test]
    fn test_header_size() {
        assert_eq!(std::mem::size_of::<VectorHeader>(), 32);
    }

    #[test]
    fn test_vocab_index_from_tsv() {
        use std::io::Write;
        let dir = std::env::temp_dir();
        let path = dir.join("mecrab_vocab_test.tsv");
        let mut f = std::fs::File::create(&path).expect("create temp vocab TSV");
        writeln!(f, "0\t東京").expect("write line 0");
        writeln!(f, "1\t大阪").expect("write line 1");
        writeln!(f, "# comment line").expect("write comment");
        writeln!(f, "2\t京都").expect("write line 2");
        drop(f);

        let idx = VocabIndex::from_tsv(&path).expect("load vocab index");
        assert_eq!(idx.surface_of(0), Some("東京"));
        assert_eq!(idx.surface_of(1), Some("大阪"));
        assert_eq!(idx.surface_of(2), Some("京都"));
        assert_eq!(idx.surface_of(99), None);
        assert_eq!(idx.len(), 3);
        assert!(!idx.is_empty());

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_vocab_index_empty() {
        let v = VocabIndex::default();
        assert!(v.is_empty());
        assert_eq!(v.len(), 0);
        assert_eq!(v.surface_of(0), None);
    }

    #[test]
    fn test_cosine_similarity() {
        let a = vec![1.0, 0.0, 0.0];
        let b = vec![1.0, 0.0, 0.0];
        assert!((VectorStore::cosine_similarity(&a, &b).unwrap() - 1.0).abs() < 1e-6);

        let a = vec![1.0, 0.0, 0.0];
        let b = vec![0.0, 1.0, 0.0];
        assert!((VectorStore::cosine_similarity(&a, &b).unwrap() - 0.0).abs() < 1e-6);

        let a = vec![1.0, 0.0, 0.0];
        let b = vec![-1.0, 0.0, 0.0];
        assert!((VectorStore::cosine_similarity(&a, &b).unwrap() + 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_f16_roundtrip() {
        // f16_to_f32(f32_to_f16(v)) ≈ v within f16 precision (~0.5% relative).
        let cases: &[f32] = &[0.0, -0.0, 1.0, -1.0, 0.5, 1024.0, -0.001, 65504.0];
        for &v in cases {
            let bits = f32_to_f16(v);
            let back = f16_to_f32(bits);
            if v == 0.0_f32 {
                assert!(back.abs() < f32::EPSILON, "zero roundtrip: got {back}");
            } else {
                let rel_err = ((back - v) / v).abs();
                assert!(
                    rel_err < 0.005,
                    "f16 roundtrip: {v} → {bits:#06x} → {back}, rel_err={rel_err}"
                );
            }
        }
        // Overflow → infinity (exponent bits = 0x7C00)
        let inf_bits = f32_to_f16(1e10_f32);
        assert_eq!(
            inf_bits & 0x7C00,
            0x7C00,
            "overflow should produce inf exponent"
        );
    }

    #[test]
    fn test_quantize_f16_roundtrip() {
        let dim = 4_usize;
        let vocab = 3_usize;
        let vecs: Vec<f32> = vec![
            1.0, -1.0, 0.5, 0.25, 0.0, 2.0, -2.0, 1.5, -0.5, 0.75, 0.1, -0.3,
        ];
        let buf = quantize_f16(&vecs, vocab, dim);
        assert_eq!(buf.len(), 32 + vocab * dim * 2, "buffer size mismatch");

        // Verify header dtype = F16
        // Header layout: magic(0..4), vocab_size(4..8), dim(8..12), data_type(12..16)
        let dtype = u32::from_le_bytes(buf[12..16].try_into().unwrap());
        assert_eq!(dtype, VectorDataType::F16 as u32, "dtype should be F16");

        // Spot-check each value via manual decode
        for (i, &orig) in vecs.iter().enumerate() {
            let byte_off = 32 + i * 2;
            let bits = u16::from_le_bytes(buf[byte_off..byte_off + 2].try_into().unwrap());
            let decoded = f16_to_f32(bits);
            let rel_err = if orig == 0.0_f32 {
                decoded.abs()
            } else {
                ((decoded - orig) / orig).abs()
            };
            assert!(
                rel_err < 0.005,
                "f16 quantize roundtrip [{i}]: orig={orig}, decoded={decoded}"
            );
        }
    }

    #[test]
    fn test_quantize_i8_roundtrip() {
        let dim = 4_usize;
        let vocab = 2_usize;
        let vecs: Vec<f32> = vec![1.0, -1.0, 0.5, 0.25, 0.0, 2.0, -2.0, 1.5];
        let (buf, scale) = quantize_i8(&vecs, vocab, dim);
        assert_eq!(buf.len(), 32 + vocab * dim, "buffer size mismatch");

        // Scale should be max_abs / 127.0
        let max_abs = vecs.iter().copied().fold(0.0_f32, |m, v| m.max(v.abs()));
        let expected_scale = max_abs / 127.0;
        assert!(
            (scale - expected_scale).abs() < 1e-7,
            "scale mismatch: {scale} vs {expected_scale}"
        );

        // Header reserved[0] must contain scale bits
        let reserved0 = u32::from_le_bytes(buf[16..20].try_into().unwrap());
        assert_eq!(
            reserved0,
            scale.to_bits(),
            "reserved[0] must contain scale bits"
        );

        // Each decoded element within one scale unit of original
        for (i, &orig) in vecs.iter().enumerate() {
            let byte_off = 32 + i;
            let q = buf[byte_off] as i8;
            let decoded = q as f32 * scale;
            let err = (decoded - orig).abs();
            assert!(
                err <= scale + 1e-6,
                "i8 quantize [{i}]: orig={orig}, q={q}, decoded={decoded}, err={err}, scale={scale}"
            );
        }
    }

    #[test]
    fn test_get_dequantized_oob_returns_none() {
        let dim = 4_usize;
        let vocab = 2_usize;
        let vecs: Vec<f32> = vec![1.0, 0.5, -0.5, 0.25, 0.0, 1.0, 2.0, -1.0];
        let buf = quantize_f16(&vecs, vocab, dim);

        // Write to a temp file and load via VectorStore::from_file
        let tmp = std::env::temp_dir().join("mecrab_test_f16_oob.mcv1");
        std::fs::write(&tmp, &buf).unwrap();
        let store = VectorStore::from_file(&tmp).expect("load store");

        assert!(
            store.get_dequantized(0).is_some(),
            "word_id=0 must be present"
        );
        assert!(
            store.get_dequantized(1).is_some(),
            "word_id=1 must be present"
        );
        assert!(
            store.get_dequantized(2).is_none(),
            "word_id >= vocab_size must return None"
        );

        let _ = std::fs::remove_file(&tmp);
    }
}
